<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("Filter", "Кузов,Тип двигателя,Цвет");
$APPLICATION->SetPageProperty("TopPager", "1471");
$APPLICATION->SetTitle("Title");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"aval-3.0", 
	array(
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "auto",
		"IBLOCK_ID" => "38",
		"NEWS_COUNT" => "99",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "AN_YER",
			1 => "AN_DVG",
			2 => "AN_DISL",
			3 => "AN_IMG",
			4 => "AN_KUZ",
			5 => "AN_KOM",
			6 => "AN_LIT",
			7 => "AN_PRI",
			8 => "AN_PRO",
			9 => "AN_KMS",
			10 => "AN_DTP",
			11 => "AN_TRA",
			12 => "AN_COL",
			13 => "AN_PRC",
			14 => "AN_RUK",
			15 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "AN_YER",
			1 => "AN_DVG",
			2 => "AN_IMG",
			3 => "AN_KUZ",
			4 => "AN_KOM",
			5 => "AN_LIT",
			6 => "AN_PRI",
			7 => "AN_PRO",
			8 => "AN_KMS",
			9 => "AN_DTP",
			10 => "AN_TRA",
			11 => "AN_COL",
			12 => "AN_PRC",
			13 => "AN_FXPR",
			14 => "AN_RUK",
			15 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SEF_FOLDER" => "/availability/",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"COMPONENT_TEMPLATE" => "aval-3.0",
		"AJAX_OPTION_ADDITIONAL" => "",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "AN_YER",
			1 => "AN_DVG",
			2 => "AN_IMG",
			3 => "AN_KUZ",
			4 => "AN_KOM",
			5 => "AN_LIT",
			6 => "AN_PRI",
			7 => "AN_PRO",
			8 => "AN_KMS",
			9 => "AN_DTP",
			10 => "AN_TRA",
			11 => "AN_COL",
			12 => "AN_PRC",
			13 => "AN_FXPR",
			14 => "AN_RUK",
			15 => "",
		),
		"CACHE_NOTES" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "/availability/",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>